import type { CreativePack, VideoDnaAnalysis } from './types';
import { compileCreativePrompts } from './compiler';

export const DEMO_ANALYSIS: VideoDnaAnalysis = {
  schema_version: 'video-dna.v1',
  source: {
    duration_seconds: 12,
    aspect_ratio: '9:16',
    language: '中文',
    format_type: '单场景微剧情 / 情绪反转短片',
    one_line_summary: '一场由误会开启、用无声动作完成反转的雨夜微剧情。',
    rights_risks: [],
  },
  style_dna: {
    hook_pattern: '前 1.5 秒用突发动作和近距离声响直接制造疑问。',
    narrative_arc: ['异常闯入', '误会升级', '动作停顿', '温柔反转', '余韵收束'],
    pacing: {
      description: '前快后慢，冲突区短镜头密集，反转后明显延长停留。',
      average_shot_seconds: 2.4,
      energy_curve: ['high', 'peak', 'medium', 'low', 'warm hold'],
      cut_pattern: '动作切入 → 视线反打 → 道具特写 → 情绪长停留。',
    },
    cinematography: {
      framing_pattern: ['手部极近景开场', '双人中近景建立空间', '单镜头焦点交换', '道具特写', '稳定近景结尾'],
      camera_motion_pattern: ['短促手持跟入', '轻微横移', '反转后稳定慢推'],
      lens_feel: '35mm 贴近人物，轻微广角临场感，反转用更浅景深隔离背景。',
      composition_rules: ['人物沿门框形成纵深', '关键道具始终处于画面下三分之一', '反转后两人进入同一构图'],
      continuity_rules: ['雨水方向保持一致', '暖光始终来自室内右侧', '关键道具从右手交到左手'],
    },
    visual: {
      medium: '写实电影感手机短片',
      palette: ['深墨绿', '湿冷蓝灰', '室内琥珀暖光'],
      lighting_logic: '门外冷雨逆光与室内单侧暖光形成明确冷暖边界。',
      textures: ['湿布料', '玻璃雨痕', '轻微高感颗粒', '真实肤质'],
      atmosphere: '紧张但克制，最后转为安静、温柔。',
    },
    performance: {
      energy: '开场动作急促，冲突后突然静止，靠呼吸和眼神完成情绪变化。',
      gesture_language: '手腕先发力、身体随后跟进；反转时动作幅度显著缩小。',
      facial_language: '先警惕皱眉，再短暂停顿，最后放松眼角而不大笑。',
      blocking_pattern: '两人先被门框分隔，理解发生后跨过边界进入同一侧。',
    },
    audio: {
      dialogue_delivery: '短句、低声、留白多；冲突句落在动作重音后半拍。',
      music_logic: '低频持续音垫底，反转时撤掉低频并进入温暖和弦。',
      sound_effects: ['门铃短响', '雨声', '纸袋摩擦', '一次清晰放下声'],
      beat_sync: '切点主要跟随门铃、纸袋落桌和人物吸气，而非持续音乐节拍。',
    },
  },
  source_roles: [
    {
      role_id: 'ROLE_A',
      entity_type: 'human',
      species: '人类 / human',
      body_plan: '成年双足人类身体结构，窄肩瘦高轮廓',
      anthropomorphism_level: 'none',
      casting_envelope: {
        apparent_age_band: '20 岁左右年轻成年人',
        gender_expression: '清爽克制的女性表达',
        regional_visual_context: '当代东亚写实微剧情选角语境',
        build_silhouette: '窄肩瘦高、动作轻快',
        hair_grooming: '黑色齐耳短发，雨水打湿后贴额',
        wardrobe_function: '简洁防雨外层与内搭，材质必须表现湿润状态',
        visual_medium: '写实电影感手机短片，真实肤质与湿材质',
      },
      narrative_function: '带着错误判断进入空间的行动者',
      generalized_appearance: '年轻成年人，轮廓利落，湿发，冷色外套。',
      silhouette: '窄肩长外套形成清晰纵向轮廓。',
      wardrobe_logic: '防雨外层与简洁内搭，材质能显出雨水。',
      performance_traits: ['动作快于语言', '先观察手部再看脸', '情绪转折克制'],
      continuity_anchors: ['湿发贴额', '右手提纸袋', '深色长外套'],
      identity_risk: 'none',
    },
    {
      role_id: 'ROLE_B',
      entity_type: 'human',
      species: '人类 / human',
      body_plan: '成年双足人类身体结构，结实稳定轮廓',
      anthropomorphism_level: 'none',
      casting_envelope: {
        apparent_age_band: '55 岁左右成熟成年人',
        gender_expression: '沉稳克制的男性表达',
        regional_visual_context: '当代东亚写实职业微剧情选角语境',
        build_silhouette: '结实稳定但不魁梧',
        hair_grooming: '花白短发，整洁实用',
        wardrobe_function: '耐磨职业工装与旧反光背心，支持检修动作',
        visual_medium: '写实电影感手机短片，真实肤质与工装磨损',
      },
      narrative_function: '承受误会并用一个动作完成反转的人',
      generalized_appearance: '成年店员，姿态稳定，暖色围裙。',
      silhouette: '卷袖衬衫与围裙形成柔和、可靠的轮廓。',
      wardrobe_logic: '耐磨棉麻材质，与空间暖光融合。',
      performance_traits: ['几乎不后退', '用视线引导关键道具', '反转后保持轻微停顿'],
      continuity_anchors: ['暖色围裙', '左手腕旧表', '袖口卷两折'],
      identity_risk: 'none',
    },
  ],
  beats: [
    {
      beat_id: 'B01',
      start_seconds: 0,
      end_seconds: 1.4,
      role_ids: ['ROLE_A'],
      narrative_function: '突发钩子',
      visual_action: '湿透的手猛推开玻璃门，纸袋擦过门框。',
      environment: '雨夜街边小店的玻璃入口，门外暴雨、门内柜台在暖光区。',
      props: ['湿纸袋', '玻璃门', '门铃'],
      framing: '手部极近景连续后撤为肩后近景',
      camera_motion: '短促手持后撤跟入，无剪切',
      composition: '门框压缩画面，人物从右侧冲入。',
      lighting: '门外冷逆光，室内暖光只勾出手部。',
      color: '冷蓝灰占主导，纸袋暖棕成为焦点。',
      sound: '门铃与雨声同时冲入。',
      dialogue: { speaker_role: '', speaker_on_screen: false, source_text: '', semantic_intent: '无对白', delivery: '', approx_characters: 0 },
      transition_in: '硬切',
      continuity_in: '纸袋在右手，衣袖滴水。',
      continuity_out: '人物站在门内但身体仍朝外。',
      confidence: 0.98,
    },
    {
      beat_id: 'B02',
      start_seconds: 1.4,
      end_seconds: 4.1,
      role_ids: ['ROLE_A', 'ROLE_B'],
      narrative_function: '误会升级',
      visual_action: '行动者把纸袋推向柜台，店员没有接，只看向袋底渗出的水。',
      // 一个不间断机位里的三次交锋：推、不接、看向渗水。整镜概括只说得清结果，说不清因果。
      action_beats: [
        { at_seconds: 1.4, actor_ids: ['ROLE_A'], action: '把湿纸袋推过柜台', toward_ids: ['ROLE_B'], reaction: '店员双手停在原处没有接', consequence: '推力落空，行动者的气势先泄了一半' },
        { at_seconds: 2.6, actor_ids: ['ROLE_B'], action: '目光下移到袋底', toward_ids: ['ROLE_A'], reaction: '行动者顺着视线低头', consequence: '注意力从追问归属转到袋底渗出的水' },
        { at_seconds: 3.4, actor_ids: ['ROLE_A'], action: '手指收紧又松开，把袋子往回收半寸', consequence: '主动权交回店员，为下一镜掀开袋角让路' },
      ],
      environment: '同一小店柜台，门框把入口冷光与室内暖光分开。',
      props: ['湿纸袋', '柜台'],
      framing: '双人中近景，单机位焦点交换',
      camera_motion: '连续轻微横移后停住',
      composition: '门框把两人分隔在画面两侧。',
      lighting: '冷暖光分别落在两人身上。',
      color: '深绿背景、暖棕围裙、冷灰外套。',
      sound: '纸袋摩擦柜台，音乐低频开始。',
      dialogue: { speaker_role: 'ROLE_A', speaker_on_screen: true, source_text: '这是你的吧？', semantic_intent: '带着怀疑确认物品归属', delivery: '压低声音，句尾上扬', approx_characters: 6 },
      transition_in: '动作匹配切',
      continuity_in: '纸袋仍在右手。',
      continuity_out: '纸袋落到柜台右侧。',
      confidence: 0.94,
    },
    {
      beat_id: 'B03',
      start_seconds: 4.1,
      end_seconds: 6.2,
      role_ids: ['ROLE_A', 'ROLE_B'],
      narrative_function: '证据揭示',
      visual_action: '店员缓慢掀开纸袋，露出一只被雨淋湿的小猫和一条干毛巾。',
      environment: '小店柜台台面，背景压暗。',
      props: ['湿纸袋', '小猫', '干毛巾'],
      framing: '道具俯拍特写，单机位抬焦至手腕动作',
      camera_motion: '稳定下压后连续轻微推近',
      composition: '纸袋居中，双手从两侧进入。',
      lighting: '一束暖光落在袋内，背景压暗。',
      color: '暖琥珀第一次成为主色。',
      sound: '纸袋展开声，音乐低频停止。',
      dialogue: { speaker_role: '', speaker_on_screen: false, source_text: '', semantic_intent: '用动作解释而非说话', delivery: '沉默', approx_characters: 0 },
      transition_in: '视线匹配切',
      continuity_in: '纸袋位于柜台右侧。',
      continuity_out: '毛巾被店员左手托起。',
      confidence: 0.96,
    },
    {
      beat_id: 'B04',
      start_seconds: 6.2,
      end_seconds: 9.1,
      role_ids: ['ROLE_A', 'ROLE_B'],
      narrative_function: '情绪反转',
      visual_action: '行动者松开攥紧的肩膀，店员把毛巾递过来，两人一起遮住袋口的雨。',
      environment: '同一小店入口与柜台之间，两人进入同一暖光区域。',
      props: ['湿纸袋', '干毛巾', '小猫'],
      framing: '双人近景',
      camera_motion: '极慢推近',
      composition: '两人跨过门框边界进入同一构图。',
      lighting: '暖光扩展到两张脸，门外冷光退成轮廓。',
      color: '暖棕与深绿平衡。',
      sound: '轻微吸气，温暖和弦进入。',
      dialogue: { speaker_role: 'ROLE_A', speaker_on_screen: true, source_text: '我以为……', semantic_intent: '承认误会但没有说完', delivery: '气声、放慢', approx_characters: 4 },
      transition_in: '呼吸停顿后切入',
      continuity_in: '毛巾在店员左手。',
      continuity_out: '两人的手同时压住毛巾边缘。',
      confidence: 0.93,
    },
    {
      beat_id: 'B05',
      start_seconds: 9.1,
      end_seconds: 12,
      role_ids: ['ROLE_A', 'ROLE_B'],
      narrative_function: '余韵收束',
      visual_action: '小猫从毛巾下探出头，两人对视后只轻轻点头。',
      environment: '同一小店柜台，玻璃门雨痕留在背景。',
      props: ['小猫', '干毛巾', '湿纸袋'],
      framing: '小猫特写拉焦到双人近景',
      camera_motion: '固定机位，单次拉焦',
      composition: '前景小猫、后景两人形成三角。',
      lighting: '柔和暖光，玻璃上雨痕保留。',
      color: '低饱和深绿与暖金。',
      sound: '雨声变远，保留一声轻微猫叫。',
      dialogue: { speaker_role: '', speaker_on_screen: false, source_text: '', semantic_intent: '无对白收束', delivery: '', approx_characters: 0 },
      transition_in: '自然动作延续',
      continuity_in: '两人的手仍在毛巾边缘。',
      continuity_out: '画面停留半秒后结束。',
      confidence: 0.97,
    },
  ],
  preserve_recommendations: ['前快后慢的节奏曲线', '门框分隔到同框的空间叙事', '冷暖光边界', '反转后撤掉低频并延长镜头', '用道具特写承担真相揭示'],
  replace_recommendations: ['人物身份与面部', '具体地点', '纸袋与小猫', '全部对白措辞', '外套与围裙的具体款式'],
  originality_risks: ['若照搬“袋中小猫”会让具体反转过近，应替换核心道具和事件。'],
  uncertainties: ['无法确认开场门铃是否为现场声或后期音效。'],
};

const DEMO_CREATIVE_PACK_BASE: CreativePack = {
  schema_version: 'creative-pack.v1',
  title: '最后一班车的白手套',
  concept_summary: '末班车站里，一名焦急学生误会检修员拿走了自己的录取材料，最终发现对方是在抢救被雨水浸湿的文件。',
  differentiation_log: ['场景轴：原创为雨夜末班车站检修室', '身份轴：原创为女大学生与年长检修员', '道具轴：原创为浸水文件、吸水纸和除湿箱', '对白轴：三句台词均按新故事重新创作', '动作轴：以抢救录取材料推进冲突与反转'],
  character_bible: [
    {
      character_id: 'CHAR_A',
      entity_type: 'human',
      species: '人类 / human',
      body_plan: '成年双足人类身体结构，窄肩瘦高轮廓',
      anthropomorphism_level: 'none',
      casting_envelope: {
        apparent_age_band: '20 岁左右年轻成年人',
        gender_expression: '清爽克制的女性表达',
        regional_visual_context: '当代东亚写实微剧情选角语境',
        build_silhouette: '窄肩瘦高、动作轻快',
        hair_grooming: '黑色齐耳短发，雨水打湿后贴额',
        wardrobe_function: '简洁防雨外层与内搭，材质必须表现湿润状态',
        visual_medium: '写实电影感手机短片，真实肤质与湿材质',
      },
      role_function: '因时间压力而错误判断的行动者',
      identity_anchors: ['短齐耳黑发', '左眉尾一颗浅痣', '瘦高轮廓', '磨旧的墨绿帆布书包'],
      appearance: '20 岁左右东亚女大学生，鹅蛋脸，清晰自然肤质，略显疲惫，眼神敏锐。',
      wardrobe: '米白连帽卫衣、深灰百褶长裙、被雨打湿的帆布鞋，材质真实且全片一致。',
      palette: ['米白', '深灰', '墨绿'],
      performance: '动作先于语言，肩颈紧绷；理解后通过放慢呼吸和松开手指完成转折。',
      continuity_lock: ['短齐耳黑发长度不变', '左眉尾浅痣保留', '墨绿帆布书包始终斜背', '服装颜色和湿润程度连续'],
      reference_prompts: {
        turnaround_sheet: '角色设定表：同一名 20 岁东亚女大学生，短齐耳黑发、左眉尾浅痣、瘦高轮廓，米白连帽卫衣、深灰百褶长裙、墨绿磨旧帆布书包。白灰纯净背景，正面、左 3/4、右侧面、背面、全身五视图等比例排列；真实电影选角照质感，50mm，中性柔光，清晰服装材质与鞋。所有格保持同一脸、同一发型、同一服装、同一人体比例。无文字、无水印、无多余人物。',
        expression_sheet: '同一角色六格表情表：焦急、怀疑、愤怒压抑、突然理解、歉意、释然；肩颈与手指动作同步变化。固定短齐耳黑发、左眉尾浅痣、米白连帽卫衣和墨绿书包，近景，统一机位与柔光，不换脸、不换衣、不夸张动漫表情。',
        hero_portrait: '雨夜末班车站内的电影感半身肖像，同一名短齐耳黑发女大学生，左眉尾浅痣，米白连帽卫衣与墨绿帆布书包，冷蓝站台光勾边、右侧暖黄检修灯照脸，真实湿发和皮肤纹理，35mm，浅景深，克制紧张。',
        negative_prompt: '不要明星脸，不要精致塑料皮肤，不要长发，不要改变浅痣位置，不要换书包或服装颜色，不要品牌 Logo，不要文字水印，不要多余手指。',
      },
    },
    {
      character_id: 'CHAR_B',
      entity_type: 'human',
      species: '人类 / human',
      body_plan: '成年双足人类身体结构，结实稳定轮廓',
      anthropomorphism_level: 'none',
      casting_envelope: {
        apparent_age_band: '55 岁左右成熟成年人',
        gender_expression: '沉稳克制的男性表达',
        regional_visual_context: '当代东亚写实职业微剧情选角语境',
        build_silhouette: '结实稳定但不魁梧',
        hair_grooming: '花白短发，整洁实用',
        wardrobe_function: '耐磨职业工装与旧反光背心，支持检修动作',
        visual_medium: '写实电影感手机短片，真实肤质与工装磨损',
      },
      role_function: '承受误会并用专业动作完成反转的人',
      identity_anchors: ['花白平头', '方正下颌', '右手旧皮表带', '橙色反光检修背心'],
      appearance: '55 岁左右东亚男性检修员，结实但不魁梧，脸上有真实工作痕迹，神情稳定。',
      wardrobe: '深蓝工装衬衫、橙色旧反光背心、耐磨工作裤、右手旧皮表带。',
      palette: ['深蓝', '旧橙', '棕黑'],
      performance: '重心稳定，不与对方争抢；先保护文件，再用视线引导对方看干燥箱。',
      continuity_lock: ['花白平头与方下颌保持', '反光背心磨损位置不变', '右手旧皮表带保留', '袖口固定卷两折'],
      reference_prompts: {
        turnaround_sheet: '角色设定表：同一名 55 岁东亚男性检修员，花白平头、方正下颌、结实身形，深蓝工装衬衫、旧橙色反光检修背心、右手棕色旧皮表带。白灰纯净背景，正面、3/4、侧面、背面、全身视图，50mm 中性柔光，真实工装磨损。所有视图同一脸、同一服装、同比例，无文字水印。',
        expression_sheet: '同一检修员六格表情：专注、被误解时平静、短暂警觉、示意等待、理解对方焦虑、温和点头。固定花白平头、方下颌、旧橙反光背心、右手旧表带，统一近景与灯光，不换脸不换装。',
        hero_portrait: '末班车站检修灯下的写实电影肖像，55 岁东亚男性检修员，花白平头、方下颌、旧橙反光背心，手持被雨水打湿的文件袋，暖黄工作灯与冷蓝站台光形成侧逆光，35mm，真实肤质与工装磨损。',
        negative_prompt: '不要名人相似，不要崭新制服，不要改变平头或表带，不要品牌标志，不要英雄海报姿势，不要塑料皮肤，不要文字。',
      },
    },
  ],
  style_lock: {
    pacing: '0-4 秒快速误会，4-6 秒证据揭示，6 秒后镜头延长并放慢。',
    camera: '手部极近景钩子、双人空间分隔、道具特写揭示、反转后稳定慢推。',
    visual: '冷蓝雨夜站台与暖黄检修灯的明确边界，湿材质、自然颗粒、低饱和深色。',
    performance: '冲突由快动作启动，反转靠停顿、呼吸和手指松开完成。',
    sound: '环境雨声与机械声主导，反转撤掉低频，结尾保留一个细小真实声响。',
    negative_constraints: ['不复制源人物脸', '不沿用源视频的具体地点、道具或事件', '不使用品牌与水印', '不做夸张争吵', '不做广告棚拍感'],
  },
  beats: [
    { beat_id: 'B01', start_seconds: 0, end_seconds: 1.4, story_function: '突发钩子', character_ids: ['CHAR_A'], action: '学生湿手推开末班车站检修门，书包撞上金属门框。', performance: '急促、呼吸凌乱。', environment: '雨夜末班车站检修门入口。', props: ['墨绿帆布书包', '金属检修门'], framing: '手部极近景连续后撤为肩后近景', camera_motion: '短促手持后撤跟入，无剪切', lighting: '门外冷蓝雨光，室内暖黄工作灯只勾手部。', continuity: '书包斜背在左肩，湿发贴额。', dialogue: '', sound: '金属门撞击、远处列车提示音与雨声。', video_prompt: '' },
    { beat_id: 'B02', start_seconds: 1.4, end_seconds: 4.1, story_function: '误会升级', character_ids: ['CHAR_A', 'CHAR_B'], action: '学生伸手去抢检修员手中的透明文件袋，检修员侧身护住袋口并看向除湿箱。', action_beats: [
      { at_seconds: 1.4, actor_ids: ['CHAR_A'], action: '伸手去抓文件袋', toward_ids: ['CHAR_B'], reaction: '检修员侧身让开半步', consequence: '抓空，学生失去先手' },
      { at_seconds: 2.6, actor_ids: ['CHAR_B'], action: '把袋口转向除湿箱示意', toward_ids: ['CHAR_A'], reaction: '学生顺着看过去', consequence: '争夺变成解释，冲突降级' },
      { at_seconds: 3.4, actor_ids: ['CHAR_A'], action: '手停在半空又收回', consequence: '把处置权交还检修员' },
    ], performance: 'CHAR_A 紧绷急切；CHAR_B 稳定克制。', environment: '站内检修室工作台，门框分隔冷暖区域。', props: ['透明文件袋', '小型除湿箱', '墨绿帆布书包'], framing: '双人中近景，单机位焦点交换', camera_motion: '连续轻横移后停住', lighting: '两人分别处于冷暖光两侧。', continuity: '文件袋在 CHAR_B 左手，CHAR_A 书包仍斜背。', dialogue: 'CHAR_A：这是你的东西吗？', sound: '塑料袋摩擦、低频持续音进入。', video_prompt: '' },
    { beat_id: 'B03', start_seconds: 4.1, end_seconds: 6.2, story_function: '证据揭示', character_ids: ['CHAR_B'], action: '检修员掀开袋角，展示吸水纸和正在运转的小型除湿箱。', performance: '动作慢而准确。', environment: '检修室工作台近处，背景压暗。', props: ['透明文件袋', '吸水纸', '小型除湿箱'], framing: '文件袋俯拍特写，单机位抬焦至手腕动作', camera_motion: '稳定下压后连续轻推', lighting: '暖光集中在湿纸边缘，背景压暗。', continuity: '旧皮表带出现在画面右下角。', dialogue: 'CHAR_B：“再晚半分钟，字就花了。”', sound: '袋角展开声，低频立即撤掉。', video_prompt: '' },
    { beat_id: 'B04', start_seconds: 6.2, end_seconds: 9.1, story_function: '情绪反转', character_ids: ['CHAR_A', 'CHAR_B'], action: '学生松开手，检修员把文件袋平放进除湿箱，两人一起压住翘起的纸角。', performance: 'CHAR_A 松开肩颈，CHAR_B 不责备。', environment: '同一检修室工作台，两人进入同一暖光区域。', props: ['透明文件袋', '吸水纸', '小型除湿箱'], framing: '双人近景', camera_motion: '极慢推近', lighting: '暖光扩展到两人脸上。', continuity: '两只手共同按住纸角，角色站到同一侧。', dialogue: 'CHAR_A：原来是我弄错了……', sound: '一次吸气，温暖和弦进入。', video_prompt: '[SHOT] 6.2-9.1s，极慢推近，两人从空间分隔进入同框，共同压住湿文件纸角；学生气声道歉，暖光扩展，真实呼吸与克制表演，9:16。' },
    { beat_id: 'B05', start_seconds: 9.1, end_seconds: 12, story_function: '余韵收束', character_ids: ['CHAR_A', 'CHAR_B'], action: '除湿箱绿灯亮起，学生看向检修员，检修员轻轻点头。', performance: '不微笑，只用眼神与点头收束。', environment: '同一检修室，窗外雨夜站台在背景。', props: ['小型除湿箱', '透明文件袋'], framing: '绿灯特写连续拉焦到双人近景', camera_motion: '固定机位单次拉焦，无剪切', lighting: '柔和暖光，窗上雨痕保留。', continuity: '两人的手仍靠近文件袋。', dialogue: '', sound: '绿灯轻响，远处列车进站声。', video_prompt: '' },
  ],
  prompt_bundle: {
    generic_master: '12 秒 9:16 写实电影感雨夜微剧情。节奏前快后慢：以湿手撞开检修门钩住注意，门框把焦急学生与年长检修员分在冷暖光两侧；文件抢夺后切吸水纸和除湿箱道具特写揭示真相；6 秒后撤掉低频、镜头变稳变长，两人进入同框共同抢救录取材料；以绿灯亮起和一次无声点头收束。所有镜头锁定 CHAR_A 与 CHAR_B 的脸、发型、工装、书包和湿润程度，真实皮肤、湿材质、轻微高感颗粒。',
    target_model: 'Veo',
    target_prompt: 'Generate a 12-second vertical 9:16 cinematic micro-drama with synchronized dialogue and environmental audio. 0-1.4s handheld hand close-up pushes into a rainy last-train maintenance room; 1.4-4.1s doorframe separates CHAR_A and CHAR_B as she reaches for a wet document sleeve; 4.1-6.2s overhead prop reveal of blotting paper and a compact drying box; 6.2-9.1s slow push-in as both enter one warm composition and save the pages; 9.1-12s green status light rack-focuses to a quiet shared nod. Cold blue rain versus warm amber work light, grounded performance, natural skin and wet fabric, restrained score, exact new Chinese dialogue from the beat list.',
    negative_prompt: 'No source faces, flower shop, paper bag, cat, logos, watermarks, celebrity likeness, glossy commercial lighting, plastic skin, exaggerated shouting, costume drift, face drift, extra fingers, random background people, duplicate subtitles.',
    first_frame_prompt: '9:16 写实电影首帧：雨夜末班车站检修门，CHAR_A 的湿手正推开金属门，米白卫衣袖口与墨绿书包边缘入画，门外冷蓝雨光、门内暖黄工作灯，手部极近景，真实湿材质与轻微颗粒。',
    last_frame_prompt: '9:16 写实电影尾帧：前景除湿箱绿灯亮起，焦点已转到后景同框的 CHAR_A 与 CHAR_B，两人安静对视轻点头，湿文件袋在画面下方，暖黄光覆盖面部，窗上冷蓝雨痕，克制余韵。',
  },
  qa: { timing_valid: true, variables_applied: true, originality_pass: true, source_identity_leakage: false, source_dialogue_leakage: false, notes: ['5 个内容轴已替换，空间分隔、节奏曲线和冷暖光逻辑被保留。'] },
};

const DEMO_SELECTED_CHARACTERS = DEMO_CREATIVE_PACK_BASE.character_bible.map((character, index) => ({
  ...character,
  candidate_id: `demo-candidate-${index + 1}`,
  source_role_id: DEMO_ANALYSIS.source_roles[index].role_id,
  design_name: `演示角色 ${index + 1}`,
  design_rationale: '用于演示 Seedance 角色参考图闭环。',
  reference_image_prompt: character.reference_prompts.hero_portrait,
}));

export const DEMO_CREATIVE_PACK = compileCreativePrompts(DEMO_CREATIVE_PACK_BASE, {
  mode: 'character_swap',
  sourceRightsScope: 'owned_or_authorized',
  newConcept: '',
  characterBrief: '',
    dialogueBrief: '英文原对白逐字保留，不翻译、不增删、不改写。',
  voiceBrief: 'CHAR_A 使用年轻、焦急但克制的自然女声；CHAR_B 使用低沉、稳定、温和的成年男声；均为全新声线，不模仿原片。',
  settingBrief: '',
  targetModel: 'Seedance 2.5',
  aspectRatio: '9:16',
    outputLanguage: 'English',
  locks: { pacing: true, camera: true, lighting: true, performance: true, sound: true, narrative: true },
  analysis: DEMO_ANALYSIS,
  selectedCharacters: DEMO_SELECTED_CHARACTERS,
  referenceAssets: DEMO_CREATIVE_PACK_BASE.character_bible.map((character, index) => ({
    asset_id: `demo-asset-${index + 1}`,
    project_id: 'demo-project',
    character_id: character.character_id,
    candidate_id: `demo-candidate-${index + 1}`,
    kind: 'identity_sheet',
    uri: `/demo-character-${index + 1}.png`,
    mime_type: 'image/png',
    prompt: character.reference_prompts.hero_portrait,
    approved: true,
    created_at: new Date(0).toISOString(),
  })),
});
