export function setupPage(token, site = '') {
  const html = value => String(value).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
  return `<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>镜感渲染助手</title><style>body{margin:0;background:#07120f;color:#e6f2ed;font:16px/1.7 system-ui}main{max-width:760px;margin:8vh auto;padding:24px}h1{font-size:32px}section{border:1px solid #284237;border-radius:20px;padding:24px;margin:24px 0}button{background:#69e4b6;border:0;border-radius:10px;padding:12px 20px;font:inherit;cursor:pointer;margin:8px 8px 8px 0}button:disabled{opacity:.4}input{box-sizing:border-box;width:100%;padding:12px;background:#102019;border:1px solid #456353;border-radius:8px;color:inherit;font:inherit}progress{width:100%;accent-color:#69e4b6}small,p{color:#b2c6bc}#error{color:#f7bba6}a{color:#69e4b6}</style><main><small>镜感 · 本机渲染助手</small><h1>准备好，开始你的 3D 预演。</h1><p>无需学习 Blender。助手会准备兼容环境并在后台渲染，已有软件不会被覆盖。</p><section><h2>渲染环境</h2><p id="status">正在检查…</p><progress id="progress" hidden></progress><div><button id="install">一键准备 Blender</button><button id="cancel" hidden>取消准备</button></div><small>首次下载约 400MB，请保留至少 3GB 空间。仅从 Blender 官方下载并校验文件。</small><p id="error" role="alert"></p><details><summary>下载受阻？导入官方离线包</summary><p>下载 Blender 4.5.3 Windows x64 ZIP，保持原文件不解压，再在这里选择。仍会校验并测试。</p><a href="https://download.blender.org/release/Blender4.5/blender-4.5.3-windows-x64.zip" target="_blank" rel="noreferrer">官方下载</a><input id="offline" type="file" accept=".zip" aria-label="Blender 离线安装包"></details></section><section><h2>连接镜感网页</h2><p>本机助手只允许你批准的网站使用。填写镜感工作台的网址，确认后返回网页点击“检查助手”。</p><input id="site" value="${html(site)}" placeholder="https://你的镜感网站" aria-label="镜感网站地址"><button id="approve">允许这个网站连接</button><p id="approved"></p></section><p>渲染时请保持助手运行。作品保存在你的电脑，安装 Blender 不会提交模型请求或产生模型费用。</p></main><script>
const token=${JSON.stringify(token)}; const q=id=>document.getElementById(id);
async function command(action,data={}){const r=await fetch('/runtime/'+action,{method:'POST',headers:{'Content-Type':'application/json','X-Mirror-Setup':token},body:JSON.stringify(data)});const v=await r.json();if(!r.ok)throw Error(v.error||'操作未完成');return v}
async function refresh(){try{const r=await fetch('/runtime/status');const s=await r.json();q('status').textContent=s.message;q('install').disabled=s.ready||!['missing','error'].includes(s.phase);q('cancel').hidden=!['downloading','verifying','extracting','checking'].includes(s.phase);q('progress').hidden=s.phase!=='downloading';q('progress').max=s.total||1;q('progress').value=s.received||0;q('approved').textContent='已允许：'+(s.origins||[]).join('、')}catch{q('status').textContent='助手连接已断开，请重新启动'}}
q('offline').onchange=async()=>{const file=q('offline').files[0];if(!file)return;q('error').textContent='' ;try{if(file.size>512*1024*1024)throw Error('文件过大');const r=await fetch('/runtime/import',{method:'POST',headers:{'X-Mirror-Setup':token},body:file});const v=await r.json();if(!r.ok)throw Error(v.error);await refresh()}catch(e){q('error').textContent=e.message}finally{q('offline').value=''}};q('install').onclick=async()=>{q('error').textContent='';try{await command('prepare');await refresh()}catch(e){q('error').textContent=e.message}};q('cancel').onclick=async()=>{try{await command('cancel')}catch(e){q('error').textContent=e.message}};q('approve').onclick=async()=>{try{await command('origin',{site:q('site').value});await refresh()}catch(e){q('error').textContent=e.message}};refresh();setInterval(refresh,1000);
</script></html>`;
}
